package org.usfirst.frc.team5590.robot;

import java.util.concurrent.TimeUnit;

import org.usfirst.frc.team5590.robot.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Noodle extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Servo noodleLiftL = RobotMap.noodleLiftL;
    Servo noodleDropL = RobotMap.noodleDropL;
    Servo noodleLiftR = RobotMap.noodleLiftR;
    Servo noodleDropR = RobotMap.noodleDropR;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    /**
     * Throws the lifting servos forward 150 degrees
     * to pick up the desired noodle 
     */
    public boolean lift(){
    	if(noodleLiftR.getAngle()<150){
    	noodleLiftL.setAngle(0);
    	noodleLiftR.setAngle(150);
    	return true;}
    	else { return false;}
    }
    /**
     * Throws the ejecting servos forward 100 degrees
     * to discard the stored noodle
     */
    public boolean eject(){
    	if(noodleDropR.getAngle()<100){
    	noodleDropL.setAngle(0);
    	noodleDropR.setAngle(100);
    	return true;
    	}
    	else{ return false;}
    }
    
    /**
     * Resets all servo motors to their base positions
     */
    public boolean resetAll(){
    	if(noodleDropR.getAngle()>0){
    	noodleLiftL.setAngle(150);
    	noodleLiftR.setAngle(0);
    	noodleDropL.setAngle(170);
    	noodleDropR.setAngle(0);
    	return true;}
    	else { return false;}
    }
    
    /**
     * Resets noodleLift servo motors to its base position
     */
    public boolean resetLift(){
    	if(noodleLiftR.getAngle()>0){
    	noodleLiftL.setAngle(150);
    	noodleLiftR.setAngle(0);
    	return true;}
    	else { return false;}
    }
    
    /**
     * Resets noodleDrop servo motors to its base position 
     */
    public boolean resetDrop(){
    	if(noodleDropR.getAngle()>0){
    	noodleDropL.setAngle(170);
    	noodleDropR.setAngle(0);
    	return true;}
    	else { return false;}
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

