package org.usfirst.frc.team5590.robot;

import java.util.concurrent.TimeUnit;

import org.usfirst.frc.team5590.robot.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Noodle extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Servo noodleLift = RobotMap.noodleLift;
    Servo noodleDrop = RobotMap.noodleDrop;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    /**
     * Throws the lifting servo forward 150 degrees
     * to pick up the desired noodle 
     */
    public void lift(){
    	noodleLift.setAngle(150);
    }
    /**
     * Throws the ejecting servo forward 100 degrees
     * to discard the stored noodle
     */
    public void eject(){
    	noodleDrop.setAngle(100);
    }
    
    /**
     * Resets all servo motors to their base positions
     */
    public void resetAll(){
    	noodleDrop.setAngle(0);
    	noodleLift.setAngle(0);
    }
    
    /**
     * Resets noodleLift servo motor to its base position
     */
    public void resetLift(){
    	noodleLift.setAngle(0);
    }
    
    /**
     * Resets noodleDrop servo to its base position 
     */
    public void resetDrop(){
    	noodleDrop.setAngle(0);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

