// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5590.robot;


import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	//Xbox Axis Numbers:
		/* 1 - LeftX
		 * 2 - LeftY
		 * 3 - Triggers(0, 1) axis value = 'left' or 'right'
		 * 4 - RightX
		 * 5 - RightY
		 * 6 - DPad Left/Right (-1 or 1)
		 * Buttons have mapping labeled in Control Panel
		 */
	// Logitech Axis Numbers
		/* 1 - X Axis
		 * 2 - Y Axis (USE!)
		 * 3 - Z (Twist)
		 * 4 - slider
		 * 5 - D Pad X
		 * 6 - D Pad Y
		 */
    
	public Joystick xbox, logitech;
	//Xbox Buttons
    public JoystickButton a, b, x, y, rightB, leftB, start, stop;
    
    //Logitech Buttons
    public JoystickButton trigger, thumb, three, four, seven, eight, nine, ten, eleven, twelve;
    
    double xboxTrigger;
    //Xbox Axis
    double xboxLeftYAxis,  xboxRightYAxis;
    //Logitech Axis
    double logYAxis, logThrottleAxis;
    

    public OI() {
    	//XBOX CONTROLLER SET UP
    	//Creates xbox controller object
        xbox = new Joystick(0);
        
        //Get left and right X axis variable (-1, 1) for the two thumbsticks.
        xboxLeftYAxis = xbox.getRawAxis(1);
        xboxRightYAxis = xbox.getRawAxis(5);
        xboxTrigger = xbox.getRawAxis(3);
        
        
        //Declare buttons here. (controller, port #)
        a = new JoystickButton(xbox, 1);
        
        b = new JoystickButton(xbox, 2);
        
        x = new JoystickButton(xbox, 3);
        
        y = new JoystickButton(xbox, 4);
        
        rightB = new JoystickButton(xbox, 6);
        leftB = new JoystickButton(xbox, 5);
        
        start = new JoystickButton(xbox, 8);
        stop = new JoystickButton(xbox, 7);

        //END XBOX CONTROLLER
        
        //START LOGITECH
        logitech = new Joystick(1);
        
        //Get Y Axis Variable
        logYAxis = logitech.getRawAxis(2);
        
        //Get Throttle Axis variable
        logThrottleAxis = logitech.getRawAxis(4);
        
        //Declare Buttons
        trigger = new JoystickButton(logitech, 1);
        
        thumb = new JoystickButton(logitech, 2);
        
        three = new JoystickButton(logitech, 3);
        
        four = new JoystickButton(logitech, 4);
        
        seven = new JoystickButton(logitech, 7);
        
        eight = new JoystickButton(logitech, 8);

        nine = new JoystickButton(logitech, 9);
        
        ten = new JoystickButton(logitech, 10);
        
        eleven = new JoystickButton(logitech, 11);
        
        twelve = new JoystickButton(logitech, 12);
        //END LOGITECH
    }
    
    public Joystick getXbox() {
        return xbox;
    }
    
    public double getXboxLeftYAxis() {
    	return xboxLeftYAxis;
    }

	public double getXboxRightYAxis() {
		return xboxRightYAxis;
	}
	
	


}

