// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5590.robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Victor slidesDrawerSlide;
    public static SpeedController drivetrainLeftTrack;
    public static SpeedController drivetrainRightTrack;
    public static RobotDrive drivetrainRobotDrive21;
    public static Solenoid autoDragDragSole;
    public static Gyro autoFinderAutoGyro;
    public static Compressor compressor;
    public static Victor liftController;
    public static Victor liftController2;
    public static Encoder liftLeft;
    public static Encoder liftRight;
    public static Encoder sliderEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	slidesDrawerSlide = new Victor(7);      
        LiveWindow.addActuator("Slides", "DrawerSlide", slidesDrawerSlide);
        
        compressor = new Compressor();
        compressor.stop();
        
        drivetrainLeftTrack = new Talon(2);
        LiveWindow.addActuator("Drivetrain", "LeftTrack", (Talon) drivetrainLeftTrack);
        
        drivetrainRightTrack = new Talon(3);
        LiveWindow.addActuator("Drivetrain", "RightTrack", (Talon) drivetrainRightTrack);
        
       
        //  LiveWindow.addActuator("Drivetrain", "RightTrack", (Talon) drivetrainRightTrack);
        
        
        drivetrainRobotDrive21 = new RobotDrive(drivetrainLeftTrack, drivetrainRightTrack);
        
        drivetrainRobotDrive21.setSafetyEnabled(false);
        drivetrainRobotDrive21.setExpiration(0.1);
        drivetrainRobotDrive21.setSensitivity(0.5);
        drivetrainRobotDrive21.setMaxOutput(1.0);
           
        autoDragDragSole = new Solenoid(0, 2);
        LiveWindow.addActuator("AutoDrag", "DragSole", autoDragDragSole);
        
        autoFinderAutoGyro = new Gyro(0);
        LiveWindow.addSensor("AutoFinder", "AutoGyro", autoFinderAutoGyro);
        autoFinderAutoGyro.setSensitivity(0.007);
        
        liftController = new Victor(8);
        liftController2 = new Victor(9);
        
        //The encoders will be in the format h2X uses the rising and falling edges to count and the B channel to determine direction
        //One encoder will be true and one will be false due to the orientation of the encoders and motors
        //The two encoders will have the same  values as defined below
        //setMinRate is the lowest inches per second value at which point the encoder will stop motion
        //setDistancePerPulse is the distance in inches per pulse from the encoder
        //setSamplesToAverage is the number of pulses it takes to determine a current speed
        
        liftLeft = new Encoder(0, 1, true, Encoder.EncodingType.k2X);
        liftLeft.setMinRate(.1);
        liftLeft.setDistancePerPulse(.014);
        liftLeft.setSamplesToAverage(30);
        
        liftRight = new Encoder(2, 3, false, Encoder.EncodingType.k2X);
        liftLeft.setMinRate(.1);
        liftLeft.setDistancePerPulse(.014);
        liftLeft.setSamplesToAverage(30);
        
        sliderEncoder = new Encoder(4, 5, false, Encoder.EncodingType.k2X);
        sliderEncoder.setMinRate(.1);
        sliderEncoder.setDistancePerPulse(.014);;
        sliderEncoder.setSamplesToAverage(30);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
