// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5590.robot;


import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class VerticalLift extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
//    public double curHeight = 0;
//    public double needHeight = 0;
//
//    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//
//    
//    // Put methods for controlling this subsystem
//    // here. Call these from Commands.
//    public void lift(double want) {
//    	needHeight = want;
//    	while (needHeight != curHeight) {
//    		liftLeft.set(.2);
//    		liftRight.set(.2);
//    		//Figure out curHeight
//    	}
//    }
//    
//    public void drop(double want) {
//    	needHeight = want;
//    	while (needHeight != curHeight) {
//    		liftLeft.set(-.2);
//    		liftRight.set(.2);
//    		//Figure out currHeight
//    	}
//    }
//    
//    public void reset(double want) {
//    	needHeight = want;
//    	//CHECK TO SEE WHAT HEIGHT IS AND RUN MOTORS TILL CURRHEIGHT == 0
//    	while (curHeight != 0) {
//    		liftLeft.set(-.2);
//    		liftRight.set(-.2);
//    		//Figure out curHeight
//    	}
//    }
//    
//    public void test() {
//    	liftLeft.set(.2);
//    }
	

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

